[package]
name = "aes-gcm-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.64"
aes-gcm = "0.10.1"
data-encoding = "2.3.2"
dotenv="0.15.0"
