[package]
name = "argon2-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.64"
argon2 = "0.4.1"
dotenv = "0.15.0"
